name: Build and Upload Artifacts

on:
  push:        # Trigger bei jedem Push
  pull_request: # Trigger bei jedem Pull Request
    branches:
      - '*'
      - '!refs/tags/*' # Optional: Tags ausschließen (falls nicht benötigt)


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1
        id: go
      # Checkout des Codes
      - name: Check out repository
        uses: actions/checkout@v4

      # Setze Abhängigkeiten auf (falls nötig)
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      # Baue das Programm mit `make cross`
      - name: Build with make cross
        run: make cross

      # Archiviere und lade das out-Verzeichnis hoch
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: out/